apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    visualize: "true"
    app: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        visualize: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.service.name }}
            topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: {{ .Values.waitTime | mul 2 }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SQS_REGION
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: aws.region
        - name: NEO_WRITER_ADDRESS
          value: "http://concepts-rw-neo4j:8080"
        - name: ES_WRITER_ADDRESS
          value: "http://concept-rw-elasticsearch:8080"
        - name: VARNISH_PURGER_ADDRESS
          value: "http://varnish-purger:8080"
        - name: CONCORDANCES_RW_ADDRESS
          value: "{{ .Values.concordances.address }}"
        - name: MAX_MESSAGES
          value: "10"
        - name: VISIBILITY_TIMEOUT
          value: "30"
        - name: WAIT_TIME
          value: "{{ .Values.waitTime }}"
        - name: HTTP_TIMEOUT
          value: "{{ .Values.httpTimeout }}"
        - name: BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: doppler-global-secrets
              key: CONCEPTS_S3_BUCKET
        - name: CONCEPTS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: doppler-global-secrets
              key: CONCEPTS_UPDATES_SQS_URL
        - name: CONCEPT_UPDATES_SNS_ARN
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: concepts.events_sns_arn
        - name: KINESIS_STREAM_NAME
          valueFrom:
            secretKeyRef:
              name: doppler-global-secrets
              key: CONCEPTS_KINESIS_STREAM
        - name: KINESIS_REGION
          valueFrom:
            secretKeyRef:
              name: doppler-global-secrets
              key: CONCEPTS_KINESIS_REGION
        - name: CROSS_ACCOUNT_ARN
          valueFrom:
            secretKeyRef:
              name: doppler-global-secrets
              key: IAM_CROSS_ACCOUNT_ARN
        ports:
        - containerPort: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/__gtg"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}

