properties:
  # General
  descriptionXML:
    neoProp: "descriptionXML"
    type: "string"
  _imageUrl:
    neoProp: "imageUrl"
    type: "string"
  emailAddress:
    neoProp: "emailAddress"
    type: "string"
  facebookPage:
    neoProp: "facebookPage"
    type: "string"
  twitterHandle:
    neoProp: "twitterHandle"
    type: "string"
  shortLabel:
    neoProp: "shortLabel"
    type: "string"
  # Brand
  strapline:
    neoProp: "strapline"
    type: "string"
  # Person
  salutation:
    neoProp: "salutation"
    type: "string"
  birthYear:
    neoProp: "birthYear"
    type: "int"
  # Membership
  inceptionDate: # not stored as a concept property so no `neoProp` needed
    type: "string"
  terminationDate: # not stored as a concept property so no `neoProp` needed
    type: "string"
  # Organisation
  countryCode:
    neoProp: "countryCode"
    type: "string"
  countryOfRisk:
    neoProp: "countryOfRisk"
    type: "string"
  countryOfIncorporation:
    neoProp: "countryOfIncorporation"
    type: "string"
  countryOfOperations:
    neoProp: "countryOfOperations"
    type: "string"
  formerNames:
    neoProp: "formerNames"
    type: "[]string"
  tradeNames:
    neoProp: "tradeNames"
    type: "[]string"
  leiCode:
    neoProp: "leiCode"
    type: "string"
  postalCode:
    neoProp: "postalCode"
    type: "string"
  properName:
    neoProp: "properName"
    type: "string"
  shortName:
    neoProp: "shortName"
    type: "string"
  yearFounded:
    neoProp: "yearFounded"
    type: "int"
  # Location
  iso31661:
    neoProp: "iso31661"
    type: "string"
  # IndustryClassification
  industryIdentifier:
    neoProp: "industryIdentifier"
    type: "string"
relationships:
  HAS_PARENT:
    conceptField: "parentUUIDs"
    neoCreate: true
    mergingStrategy: "overwrite"
  HAS_BROADER:
    conceptField: "broaderUUIDs"
    mergingStrategy: "overwrite"
  IS_RELATED_TO:
    conceptField: "relatedUUIDs"
    mergingStrategy: "overwrite"
  SUPERSEDED_BY:
    conceptField: "supersededByUUIDs"
    mergingStrategy: "overwrite"
  IMPLIED_BY:
    conceptField: "impliedByUUIDs"
  HAS_FOCUS:
    conceptField: "hasFocusUUIDs"
  # Membership
  HAS_ORGANISATION:
    conceptField: "organisationUUID"
    oneToOne: true
    neoCreate: true
    mergingStrategy: "overwrite"
  HAS_MEMBER:
    conceptField: "personUUID"
    oneToOne: true
    neoCreate: true
    mergingStrategy: "overwrite"
  HAS_ROLE: # NB: currently not in concepts-rw-neo4j
    conceptField: "membershipRoles"
    mergingStrategy: "aggregate"
    properties:
      inceptionDate: date
      terminationDate: date
  # Organisation
  COUNTRY_OF_RISK:
    conceptField: "countryOfRiskUUID"
    oneToOne: true
    neoCreate: true
  COUNTRY_OF_INCORPORATION:
    conceptField: "countryOfIncorporationUUID"
    oneToOne: true
    neoCreate: true
  COUNTRY_OF_OPERATIONS:
    conceptField: "countryOfOperationsUUID"
    oneToOne: true
    neoCreate: true
  SUB_ORGANISATION_OF:
    conceptField: "parentOrganisation"
    oneToOne: true
    neoCreate: true
  HAS_INDUSTRY_CLASSIFICATION:
    conceptField: "naicsIndustryClassifications"
    mergingStrategy: "aggregate"
    properties:
      rank: int
authorities:
