fields:
  # General
  descriptionXML:
    neoProp: "descriptionXML"
    type: "string"
  _imageUrl:
    neoProp: "imageUrl"
    type: "string"
  emailAddress:
    neoProp: "emailAddress"
    type: "string"
  facebookPage:
    neoProp: "facebookPage"
    type: "string"
  twitterHandle:
    neoProp: "twitterHandle"
    type: "string"
  shortLabel:
    neoProp: "shortLabel"
    type: "string"
  # Brand
  strapline:
    neoProp: "strapline"
    type: "string"
  # Person
  salutation:
    neoProp: "salutation"
    type: "string"
  birthYear:
    neoProp: "birthYear"
    type: "int"
  # Membership
  inceptionDate: # not stored as a concept property so no `neoProp` needed
    type: "string"
  terminationDate: # not stored as a concept property so no `neoProp` needed
    type: "string"
  # Organisation
  countryCode:
    neoProp: "countryCode"
    type: "string"
  countryOfRisk:
    neoProp: "countryOfRisk"
    type: "string"
  countryOfIncorporation:
    neoProp: "countryOfIncorporation"
    type: "string"
  countryOfOperations:
    neoProp: "countryOfOperations"
    type: "string"
  formerNames:
    neoProp: "formerNames"
    type: "[]string"
  tradeNames:
    neoProp: "tradeNames"
    type: "[]string"
relationships:
authorities:
