fields:
  # General
  descriptionXML:
    neoProp: "descriptionXML"
    type: "string"
  _imageUrl:
    neoProp: "imageUrl"
    type: "string"
  emailAddress:
    neoProp: "emailAddress"
    type: "string"
  facebookPage:
    neoProp: "facebookPage"
    type: "string"
  twitterHandle:
    neoProp: "twitterHandle"
    type: "string"
  shortLabel:
    neoProp: "shortLabel"
    type: "string"
  # Brand
  strapline:
    neoProp: "strapline"
    type: "string"
  # Person
  salutation:
    neoProp: "salutation"
    type: "string"
  birthYear:
    neoProp: "birthYear"
    type: "int"
relationships:
authorities:
