swagger: "2.0"
info:
  description: "API specification for the aggregate concept transformer"
  version: "1.0.0"
  title: "Aggregate Concept Transformer"
host: api.ft.com
schemes:
  - http
  - https
basePath: /

paths:
  /concept/{uuid}:
    get:
      summary: Get aggregate concept
      description: Retrieve concorded JSON model for given uuid
      parameters:
      - name: uuid
        in: path
        description: The UUID of the concept to be retrieved from S3
        required: true
        type: string
      - name: publication
        in: query
        description: The UUID of the publication of the concept when applicable 
        type: string
      responses:
        200:
          description: Returns concorded JSON model.
        400:
          description: Concept not found in S3 bucket.
        503:
          description: No response from S3 bucket.
  /concept/{uuid}/send:
      post:
        summary: Get aggregate concept and send to Neo4j and Elasticsearch
        description: Retrieve concorded JSON model for given uuid
        parameters:
        - name: uuid
          in: path
          description: The UUID of the concept to be retrieved from S3
          required: true
          type: string
        responses:
          200:
            description: Returns concorded JSON model.
          400:
            description: Concept not found in S3 bucket.
          503:
            description: No response from S3 bucket.